version: '3'
services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=nerd_herder
    volumes:
      - './.docker-data/postgresql/data:/var/lib/postgresql/data/'
  redis:
    image: 'redis:alpine'
  nerd_herder:
    build: .
    command: ['./wait-for-it.sh', 'postgres:5432', '--', 'python', 'manage.py', 'runserver',
    '0.0.0.0:8080']
    environment:
      - POSTGRES_USER=nerd_herder
      - POSTGRES_PASSWORD=nerd_herder
      - DEBUG=TRUE
    volumes:
      - './nerd_herder/:/usr/src/nerd_herder/nerd_herder/'
      - './config/:/usr/src/nerd_herder/config/'
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
  # TODO: Add service for react build. Probably don't need caddy that way though.
  reverse_proxy:
    image: abiosoft/caddy:0.11.0-no-stats
    restart: always
    depends_on:
      - nerd_herder
    links:
      - nerd_herder
    volumes:
      - './.docker-data/caddy:/root/.caddy'
      - './Caddyfile.dev:/etc/Caddyfile'
    ports:
      - '8080:8080'
