version: '3'
services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=nerd_herder
    volumes:
      - './.docker-data/postgresql/data:/var/lib/postgresql/data/'
  redis:
    image: 'redis:alpine'
  nerd_herder:
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_USER=nerd_herder
      - POSTGRES_PASSWORD=nerd_herder
      - DEBUG=FALSE
      - ASSET_MANIFEST_HOST=reverse_proxy:8080
    volumes:
      - './nerd_herder/:/usr/src/nerd_herder/nerd_herder/'
      - './config/:/usr/src/nerd_herder/config/'
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
  reverse_proxy:
    build:
      context: .
      dockerfile: docker/reverse_proxy/Dockerfile
    environment:
      - ACME_AGREE=true
    restart: always
    depends_on:
      - nerd_herder
    links:
      - nerd_herder
    volumes:
      - './.docker-data/caddy:/root/.caddy'
      - './Caddyfile.stg:/etc/Caddyfile'
    ports:
      - '8080:8080'
