version: '3'
services:
  postgres:
    image: postgres:latest
    env_file:
      - postgres.dev.env
    volumes:
      - './.docker-data/postgresql/data:/var/lib/postgresql/data/'
  redis:
    image: 'redis:alpine'
  nerd_herder:
    build:
      context: .
      dockerfile: docker/nerd_herder/Dockerfile
    image: registry.gitlab.com/cache-rules/nerd_herder_ops/nerd_herder:latest
    command:
      - './wait-for-it.sh'
      - 'postgres:5432'
      - '--'
      - 'python'
      - 'manage.py'
      - 'runserver'
      - '0.0.0.0:8080'
    env_file:
      - nerd_herder.dev.env
      - slack.dev.env
    volumes:
      - './nerd_herder/:/usr/src/nerd_herder/nerd_herder/'
      - './config/:/usr/src/nerd_herder/config/'
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    image: registry.gitlab.com/cache-rules/nerd_herder_ops/frontend:latest
    command:
      - 'yarn'
      - 'start'
    volumes:
        - './frontend/public/:/usr/src/nerd_herder/frontend/public'
        - './frontend/src/:/usr/src/nerd_herder/frontend/src'
        - './frontend/package.json:/usr/src/nerd_herder/frontend/package.json'
        - './frontend/yarn.lock:/usr/src/nerd_herder/frontend/yarn.lock'
  reverse_proxy:
    image: abiosoft/caddy:1.0.0-no-stats
    environment:
      - ACME_AGREE=true
    depends_on:
      - nerd_herder
      - frontend
    links:
      - nerd_herder
      - frontend
    volumes:
      - './.docker-data/caddy:/root/.caddy'
      - './Caddyfile.dev:/etc/Caddyfile'
    ports:
      - '8080:8080'
