version: '3'
services:
  postgres:
    env_file:
      - postgres.env
    volumes:
      - '/var/lib/postgresql/data:/var/lib/postgresql/data/'
  redis:
    image: 'redis:alpine'
  nerd_herder:
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    env_file:
      - nerd_herder.env
    links:
      - redis
      - postgres
  reverse-proxy:
    build:
      context: .
      dockerfile: docker/reverse_proxy/Dockerfile
    restart: always
    env_file:
      - caddy.env
    links:
      - nerd_herder
    depends_on:
      - nerd_herder
    volumes:
      - '/var/lib/caddy:/root/.caddy'
      - './Caddyfile:/etc/Caddyfile'
    ports:
      - '80:80'
      - '443:443'
