# Generated by Django 2.0.1 on 2018-02-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuecontact',
            name='job_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
