# Generated by Django 2.0.1 on 2018-02-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180205_0803'),
        ('venues', '0002_auto_20180202_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuecontact',
            name='venue',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.DeleteModel(
            name='VenueContact',
        ),
    ]
