# Generated by Django 2.0.1 on 2018-05-31 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("companies", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(name="company", options={"verbose_name_plural": "Companies"})
    ]
