# Generated by Django 2.2 on 2019-06-04 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('talk_proposals', '0002_auto_20180611_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceChoice',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
