# Generated by Django 2.0.1 on 2018-02-02 05:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkInvitation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invited_on', models.DateTimeField(auto_now_add=True)),
                ('accepted_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='talks',
            field=models.ManyToManyField(through='events.TalkInvitation', to='speakers.Talk'),
        ),
        migrations.AddField(
            model_name='talkinvitation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='talkinvitation',
            name='talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speakers.Talk'),
        ),
    ]
