# Generated by Django 2.0.1 on 2018-02-05 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('events', '0002_auto_20180202_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('value', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.CompanyContact')),
            ],
        ),
        migrations.CreateModel(
            name='VenueSponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventsponsorship',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventsponsorship',
            name='primary_contact',
        ),
        migrations.RemoveField(
            model_name='eventsponsorship',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='sponsorcontact',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='event',
            name='primary_contact',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sponsors',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.DeleteModel(
            name='EventSponsorship',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
        migrations.DeleteModel(
            name='SponsorContact',
        ),
        migrations.AddField(
            model_name='venuesponsorship',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='venuesponsorship',
            name='sponsor_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_sponsorships', to='companies.CompanyContact'),
        ),
        migrations.AddField(
            model_name='venuesponsorship',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Venue'),
        ),
        migrations.AddField(
            model_name='venuesponsorship',
            name='venue_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_contacts', to='companies.CompanyContact'),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Event'),
        ),
    ]
