# Generated by Django 2.0.1 on 2018-05-15 05:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("email_confirmed", models.BooleanField(default=False)),
                ("bio", models.TextField(blank=True, null=True)),
                ("photo", models.URLField(blank=True, null=True)),
            ],
            options={"abstract": False},
        )
    ]
