# Generated by Django 2.0.1 on 2018-02-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='talk',
            name='talk_type',
            field=models.CharField(choices=[('full_length', 'Full Length (25+ minutes)'), ('lightning', 'Lightning Talk (5-10 minutes)')], max_length=64),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
